0:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 26
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
1:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
2:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
3:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
4:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
5:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
6:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
7:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
8:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
9:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
10:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
11:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
12:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
13:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
14:
  att: !bitarray '000'
  baseline_e: !bitarray '110'
  baseline_t: 25
  branch_en_eq: !bitarray '1'
  branch_en_t: !bitarray '1'
  counter_mode: !bitarray '1111'
  dead_time: 0
  debug_mode: !bitarray '00'
  e_hysteresis: !bitarray '010'
  fe_delay: !bitarray '10000'
  fe_tp_en: !bitarray '00'
  hysteresis_en_n: !bitarray '1'
  integ_source_sw: !bitarray '00'
  intg_en: !bitarray '0'
  intg_signal_en: !bitarray '0'
  max_intg_time: 34
  min_intg_time: 34
  output_en: !bitarray '00'
  postamp_gain_e: !bitarray '00'
  postamp_gain_t: !bitarray '00'
  postamp_sh_e: !bitarray '00'
  qdc_mode: !bitarray '0'
  qtx2_en: !bitarray '0'
  sync_chain_length: !bitarray '00'
  t1_hysteresis: !bitarray '010'
  t2_hysteresis: !bitarray '010'
  tac_max_age: !bitarray '11110'
  tac_min_age: !bitarray '01010'
  tdc_current_e: 0
  tdc_current_t: 0
  trigger_b_latched: !bitarray '0'
  trigger_mode_1: !bitarray '00'
  trigger_mode_2_b: !bitarray '000'
  trigger_mode_2_e: !bitarray '000'
  trigger_mode_2_q: !bitarray '00'
  trigger_mode_2_t: !bitarray '00'
  vth_e: 19
  vth_t1: 0
  vth_t2: 0
15:
  att: !bitarray '000'
  baseline_e