name: petalo
dependencies:
  - bitarray=1.4.0
  - jupyterlab=2.2.6
  - matplotlib=3.3.1
  - numpy=1.19.1
  - pandas=1.1.3
  - pip=20.2.3
  - pymysql=0.10.1
  - pyqt=5.9.2
  - pytables=3.6.1
  - python=3.8.5
  - pip:
    - pytest==6.1.1
    - pytest-qt==3.3.0
    - pyuic5-tool==0.0.1
